name: Lint Service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'service/**'

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: service/package-lock.json

      - name: Install dependencies
        working-directory: service
        run: npm ci

      - name: Run ESLint
        working-directory: service
        run: npm run lint
