name: Test service

on:
  pull_request:
    branches:
      - main
    paths:
      - 'service/**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: service/package-lock.json

      - name: Install dependencies
        working-directory: service
        run: npm ci

      - name: Run tests
        working-directory: service
        run: npm test


